Print res.text instead of res.json() on error
When getting an unexpected response, we cannot be sure that it is proper
json. I got this error:

```
Repsonse:
Traceback (most recent call last):
  File "update_dns_record.py", line 324, in <module>
  File "update_dns_record.py", line 54, in main
  File "update_dns_record.py", line 202, in get_record_json
  File "update_dns_record.py", line 101, in send_request
  File "update_dns_record.py", line 230, in make_api_url
  File "update_dns_record.py", line 257, in get_record_id
  File "update_dns_record.py", line 129, in send_request
  File "requests/models.py", line 898, in json
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```